// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n= Integer.parseInt(args[0]);
		int lowerThanHalf = 0;
		int biggerThanHalf = 0;
		for ( int i=0; i<n; i++){
			double result= Math.random();
			if (result <= 0.5)
			lowerThanHalf++;
			else biggerThanHalf++;

		}
		System.out.println(" > 0.5: " + biggerThanHalf + " times");
		System.out.println(" <= 0.5: " + lowerThanHalf + " times");
		if (lowerThanHalf!=0){
		double ratio = (double) biggerThanHalf / lowerThanHalf ; 
		System.out.println("Ratio:" + ratio);
		}
	}
}
